# Generated by Django 5.0.6 on 2024-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customer_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='details',
            field=models.CharField(max_length=255),
        ),
    ]
