# Generated by Django 5.0.6 on 2024-06-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
