# Generated by Django 5.0.6 on 2024-06-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_package_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='gps_tracking_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
